### ISSUE TITLE
What is the scope of this project?

### ISSUE THREAD

**Issue by yeya24** [breeswish/prometheus-dumper#1]
Hello :wave:, this repo seems interesting and I am curious about its usage and scope.

Prometheus already has a snapshot API https://prometheus.io/docs/prometheus/latest/querying/api/#snapshot, which can be used to backup all the blocks in disk and also dump in-memory TSDB head to disk as well. Is this the same thing you want to achieve in this project?

**Comment by breezewish** [comment]
Hi, @yeya24 This project is based on the snapshot feature, additionally filter out unneeded time ranges.

**Comment by yeya24** [comment]
Thanks for the reply! This sounds very useful since the Snapshot API doesn't support time range. But it would be better to try to add this feature in the upstream Prometheus itself, like adding time range params to the snapshot API, wdyt?

**Comment by breezewish** [comment]
@yeya24 Thanks for the suggestion! It is a good idea! I will investigate how this feature can be contributed to the Prometheus when I have a prototype implementation. However this project may continue exist since I plan to use it for existing Prometheus deployments as well.
